//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Divisio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accounts()
        {
            this.algemene_groepen = new HashSet<algemene_groepen>();
            this.contactlijst = new HashSet<contactlijst>();
            this.contactlijst1 = new HashSet<contactlijst>();
            this.items = new HashSet<items>();
            this.lening = new HashSet<lening>();
        }
    
        public int IdAccount { get; set; }
        public string Usernaam { get; set; }
        public string Paswoord { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Actief { get; set; }
        public int AccountType_IdAccountType { get; set; }
        public int Users_IdUser { get; set; }
    
        public virtual users users { get; set; }
        public virtual accountType accountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<algemene_groepen> algemene_groepen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactlijst> contactlijst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactlijst> contactlijst1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<items> items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lening> lening { get; set; }
    }
}
