//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Divisio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public items()
        {
            this.lening = new HashSet<lening>();
            this.categorie = new HashSet<categorie>();
            this.groepen = new HashSet<groepen>();
        }
    
        public int IdItem { get; set; }
        public string ItemNaam { get; set; }
        public string Beschrijving { get; set; }
        public byte Beschikbaar { get; set; }
        public string Foto_Path { get; set; }
        public Nullable<int> Accounts_IdAccount { get; set; }
        public Nullable<int> Toestand_IdToestand { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual toestand toestand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lening> lening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categorie> categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<groepen> groepen { get; set; }
    }
}
