//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Divisio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lening
    {
        public int IdLening { get; set; }
        public System.DateTime Begindatum { get; set; }
        public Nullable<System.DateTime> Einddatum { get; set; }
        public string Opmerking { get; set; }
        public Nullable<double> Beoordeling { get; set; }
        public Nullable<int> Accounts_IdAccount { get; set; }
        public Nullable<int> Items_IdItem { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual items items { get; set; }
    }
}
